config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: "users/confirmations",
                                    passwords: "users/passwords",
                                    registrations: "users/registrations",
                                    sessions: "users/sessions",
                                    unlocks: "users/unlocks",
                                    omniauth: "users/omniauth" }
  resources :profiles
  resources :fastorders
  resources :orders
  root 'photos#index'
  get 'photos/hoodie'
  get 'photos/tv'
  get 'photos/iphone'
  get 'photos/shoe'
  get 'photos/cream'
  get 'photos/speaker'

end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
    @profile = Profile.find_by(params[:id])
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find_by(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :address, :phone, :zip_code, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% if current_user.profile == nil%>
  <div class="field">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"first name" %>
  </div>

  <div class="field">
    <% form.label :last_name, class:"form-label" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"last name" %>
  </div>

  <div class="field">
    <% form.label :address %>
    <%= form.text_field :address, class:"form-control", placeholder:"address" %>
  </div>

  <div class="field">
    <% form.label :phone %>
    <%= form.text_field :phone, class:"form-control", placeholder:"phone" %>
  </div>

  <div class="field">
    <% form.label :zip_code %>
    <%= form.text_field :zip_code, class:"form-control", placeholder:"zip code" %>
  </div>
  <div class="actions create">
    <%= form.submit class:"btn btn-danger btn-sm", value:"Create" %>
  </div>
  
<% else %>
  <div class="field">
    <%= form.label :first_name, class:"form-label" %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :last_name, class:"form-label" %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :address, class:"form-label" %>
    <%= form.text_field :address, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :phone, class:"form-label" %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :zip_code, class:"form-label" %>
    <%= form.text_field :zip_code, class:"form-control" %>
  </div>

   <div class="actions update">
    <%= form.submit class:"btn btn-danger btn-sm", value:"Update" %>
  </div>
<% end %>
  <div class="field">
    <% form.label :user_id %>
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>
 
<% end %>

app/views/profiles/edit.html.erb
<div class="edit-profile row">
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>
<%= link_to "Cancel", @profile, class:"btn btn-info btn-sm back" %>
</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Zip code</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.address %></td>
        <td><%= profile.phone %></td>
        <td><%= profile.zip_code %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<div class="create-profile row">
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', root_path, class:"btn btn-sm btn-info" %>
</div>

app/views/profiles/show.html.erb
<% if notice %>
<div class="profile-notice alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>
<div class="profile">
<h1>My Profile</h1>

<p>
  <strong>Name:</strong>
  <%= @profile.first_name + ' ' + @profile.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @profile.phone %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @profile.zip_code %>
</p>
<div id="profile-account">
<%= link_to 'Edit', edit_profile_path(@profile), class:"btn btn-info btn-sm" %> 
<%= link_to 'Update account', edit_user_registration_path, class:"btn btn-danger btn-sm" %>
<%= link_to 'Home', root_path, class:"btn btn-sm btn-info" %>
</div>
</div>