config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: "users/confirmations",
                                    passwords: "users/passwords",
                                    registrations: "users/registrations",
                                    sessions: "users/sessions",
                                    unlocks: "users/unlocks",
                                    omniauth: "users/omniauth" }
  resources :profiles
  resources :fastorders
  resources :orders
  root 'photos#index'
  get 'photos/hoodie'
  get 'photos/tv'
  get 'photos/iphone'
  get 'photos/shoe'
  get 'photos/cream'
  get 'photos/speaker'

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  end

  def shoe
  end

  def cream
  end 

  def hoodie
  end

  def iphone
  end

  def speaker
  end

  def tv 
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/cream.html.erb
<div class="product-container">
    <% if user_signed_in? %>
    <% if current_user.profile != nil %>
    <% end %>
    <% end %>
    <h1>Visit the L'Oreal Paris Store</h1>
    <p class="info">
        L'Oreal Paris Skincare Collagen Face Moisturizer, Day and Night 
        Cream, Anti-Aging Face, Neck and Chest Cream to smooth skin 
        and reduce wrinkles, 1.7 oz
    </p>
    <%= image_tag("products/cream.jpg")%>
    <br>
    <br>
    <%= link_to 'Back', :back, class:"btn btn-info btn-sm" %>
    <% if !user_signed_in? %>
    <%= link_to "Order Now", new_fastorder_path(name: 'cream'), class: "btn btn-warning btn-sm" %>
    <% else %>
    <%= link_to "Order Now", new_order_path(name: 'cream'), class: "btn btn-warning btn-sm" %>
    <% end %>
    <h3>DESCRIPTION</h3>
    <p class="description">
        A dose of intense hydration and natural Collagen in Collagen Filler Moisturizer
        Day Lotion and Day/Night Cream is essential for younger-looking skin. Rich
        moisture instantly restores skin's cusion and bounce. Over time, the powerful 
        natural Collagen helps fill in lines and wrinkles, leaving your skin smooth
        and plump. Use it for a complete Collagen-infused skincare regimen. *Based on 
        comsumer evaluation of 50 women.
    </p>
</div>

app/views/photos/hoodie.html.erb
<div class="product-container">
    <% if user_signed_in? %>
    <% if current_user.profile != nil %>
    <% end %>
    <% end %>
    <h1>Visit the Gildan Store</h1>
    <p class="info">Men's Fleece Hooded Sweatshirt, Style G18900</p>
    <%= image_tag("products/hoodie.jpg")%>
    <br>
    <br>
    <%= link_to 'Back', :back, class:"btn btn-info btn-sm" %>
    
    <% if !user_signed_in? %>
    <%= link_to "Order Now", new_fastorder_path(name: 'hoodie'), class:"btn btn-warning btn-sm" %>
    <% else %>
    <%= link_to "Order Now", new_order_path(name: 'hoodie'), class:"btn btn-warning btn-sm" %>
    <% end %>
    <h3>DESCRIPTION</h3>
    <p class="description">
        When it comes to warm and cozy cool-weather wear, the Gildan Heavy Blend 
        hooded sweatshirt is always the perfect call. Offering the weighty pullover 
        feel of 8.0 oz.per sq. yd., it offers the kind of grab-and-go comfort 
        you'll want on a chilly afternoon or a crisp evening. Made from a 50% cotton
        / 50% polyester blend, it's the one hoodie every wardrobe deserves.
    </p>
</div>

app/views/photos/index.html.erb
<h1 id="photos-index-h1">Select an item to order instantly</h1>

<div class="photo-container">
<div class="row row-cols-2">

    <div class="grid-item">
    <div class="inner-item">
    <%= link_to image_tag('thumbnails/shoe.jpg'), photos_shoe_path(name: 'shoe.jpg')%>
    <a href="photos/shoe"><p>Men's Hypebeast 1 Sports <br> Running Shoes<br><strong>Rs. 2000</strong></p></a>
    </div>
    </div>

    <div class="grid-item">  
    <div class="inner-item"> 
    <%= link_to image_tag('thumbnails/cream.jpg'), photos_cream_path(name: 'cream.jpg')%>
    <a href="photos/cream"><p>L'Oreal Paris Skincare Collagen Face<br>Moisturizer, Day and Night Cream<br>
        <strong>Rs. 450</strong></p></a>
    </div>
    </div>

    <div class="grid-item">
    <div class="inner-item">
    <%= link_to image_tag('thumbnails/hoodie.jpg'), photos_hoodie_path(name: 'hoodie.jpg')%>
    <a href="photos/hoodie"><p>Columbia Men's Ascender<br>Softshell Front-zip Jacket<br>
        <strong>Rs. 2500</strong></p></a>
    </div>
    </div>

    <div class="grid-item">
    <div class="inner-item">
    <%= link_to image_tag('thumbnails/iphone.jpeg'), photos_iphone_path(name: 'iphone.jpeg')%>
    <a href="photos/iphone"><p>Apple iPhone 11(128GB)<br>Sim-Free<br><strong>Rs. 55000</strong></p></a>
    </div>
    </div>

    <div class="grid-item">
    <div class="inner-item">
    <%= link_to image_tag('thumbnails/speaker.jpg'), photos_speaker_path(name: 'speaker.jpg')%>
    <a href="photos/speaker"><p>JBL FLIP 4 - Waterproof Portable<br>Bluetooth Speaker - Black<br>
        <strong>Rs. 1500</strong></p></a>
    </div>
    </div>

    <div class="grid-item">
    <div class="inner-item">
    <%= link_to image_tag('thumbnails/tv.jpg'), photos_tv_path(name: 'tv.jpg')%>
    <a href="photos/tv"><p>SAMSUNG 85-inch Class Crystal UHD<br>TU-800 Series<br><strong>Rs. 44000</strong></p></a>
    </div>
    </div>
    
</div>
</div>

app/views/photos/iphone.html.erb
<div class="product-container">
<% if user_signed_in? %>
    <% if current_user.profile != nil %>
    <% end %>
    <% end %>
    <h1>Apple</h1>
    <p class="info">Apple iPhone 11(128GB) Sim-Free</p>
    <%= image_tag("products/iphone.jpeg")%>
    <br>
    <br>
    <%= link_to 'Back', :back, class:"btn btn-info btn-sm" %>

    <% if !user_signed_in? %>
    <%= link_to "Order Now", new_fastorder_path(name: 'hoodie'), class:"btn btn-warning btn-sm"%>
    <% else %>
    <%= link_to "Order Now", new_order_path(name: 'hoodie'), class:"btn btn-warning btn-sm"%>
    <% end %>
    <h3>DESCRIPTION</h3>
    <p class="description">
        iPhone 11 mini packs big features in a 5.4-inch design. A beautifully bright
        and compact Super Retina XDR display. Ceramic Shield with four times better
        drop performance. Incredible low light photography with Night mode on all 
        cameras. Cinema grade Dolby Vision HDR video recording, editing and playback.
    </p>
</div>

app/views/photos/shoe.html.erb
<div class="product-container">
    <% if user_signed_in? %>
    <% if current_user.profile != nil %>
    <% end %>
    <% end %>
    <h1>Visit the Under Armour Store</h1>
    <p class="info">Men's Hypebeast 1 Sports Running Shoes</p>
    <%= image_tag("products/shoe.jpg")%>
    <br>
    <br>
    <%= link_to 'Back', :back, class:"btn btn-info btn-sm" %>    
    <% if !user_signed_in? %>
    <%= link_to "Order Now", new_fastorder_path(name: 'shoe'), class:"btn btn-warning btn-sm" %>
    <% else %>
    <%= link_to "Order Now", new_order_path(name: 'shoe'), class:"btn btn-warning btn-sm" %>
    <% end %>
    <h3>DESCRIPTION</h3>
    <p class="description">
        Neutral for runners who need a balance and flexibility and cushioning. 
        Lightweight mesh upper with 3-color digital print delivers complete breathability.
    </p>
</div>

app/views/photos/speaker.html.erb
<div class="product-container">
    <% if user_signed_in? %>
    <% if current_user.profile != nil %>
    <% end %>
    <% end %>
    <h1>Visit the JBL Store</h1>
    <p class="info">JBL FLIP 4 - Waterproof Portable Bluetooth Speaker - Black</p>
    <%= image_tag("products/speaker.jpg")%>
    <br>
    <br>
    <%= link_to 'Back', :back, class:"btn btn-info btn-sm" %>

    <% if !user_signed_in? %>
    <%= link_to "Order Now", new_fastorder_path(name: 'speaker'), class:"btn btn-warning btn-sm" %>
    <% else %>
    <%= link_to "Order Now", new_order_path(name: 'speaker'), class:"btn btn-warning btn-sm" %>
    <% end %>
    <h3>DESCRIPTION</h3>
    <p class="description">
        JBL FLIP 4 is the next generation in the Flip series; it is a portable 
        Bluetooth speaker that delivers surprisingly powerful stereo sound. This
        compact speaker is powered by a 3000mAh rechargeableLi-ion battery that 
        offers 12 hours of continuous, high quality audio playtime. Sporting durable,
        waterproof fabric materials that are available in 6 vibrant colors, Flip 4
        is the all purpose, all weather compannion that takes the party everywhere.
    </p>
</div>

app/views/photos/tv.html.erb
<div class="product-container">
    <% if user_signed_in? %>
    <% if current_user.profile != nil %>
    <% end %>
    <% end %>
    <h1>Visit the Samsung Store</h1>
    <p class="info">SAMSUNG 85-inch Class Crystal UHD TU-800 Series</p>
    <%= image_tag("products/tv.jpg")%>
    <br>
    <br>
    <%= link_to 'Back', :back, class:"btn btn-info btn-sm" %>
    
    <% if !user_signed_in? %>
    <%= link_to "Order Now", new_fastorder_path(name: 'tv'), class:"btn btn-warning btn-sm" %>
    <% else %>
    <%= link_to "Order Now", new_order_path(name: 'tv'), class:"btn btn-warning btn-sm" %>
    <% end %>
    <h3>DESCRIPTION</h3>
    <p class="description">
        Experience immersive viewing when you add this Samsung 40 in. Smart TV to your
        home. The wide color enhancer and Full HD resolution deliver vibrant picture
        quality, while the Digital Clena view optimizes content for better results.
        A unique lifestyle gallery creates scenic views for any room in your home 
        when this TV is not in use. It also features support for Samsung Smart things
        app to complete your home automation step.
    </p>
</div>