config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: "users/confirmations",
                                    passwords: "users/passwords",
                                    registrations: "users/registrations",
                                    sessions: "users/sessions",
                                    unlocks: "users/unlocks",
                                    omniauth: "users/omniauth" }
  resources :profiles
  resources :fastorders
  resources :orders
  root 'photos#index'
  get 'photos/hoodie'
  get 'photos/tv'
  get 'photos/iphone'
  get 'photos/shoe'
  get 'photos/cream'
  get 'photos/speaker'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
  <ul class="navbar-nav">
    <li class="nav-item active">
        <%= link_to 'Home', root_path, class:"nav-link" %>
    </li>    
    <li class="nav-item">
        <%= link_to 'About Us', root_path, class:"nav-link" %>
    </li> 
    <li class="nav-item">
        <%= link_to 'Orders', fastorders_path, class:"nav-link" %>
    </li>
    <% if user_signed_in? %>
    <li class="nav-item">
        <%= link_to 'My Orders', orders_path, class:"nav-link" %>
    </li> 
    <li class="nav-item">
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"nav-link" %>
    </li>
    <% if current_user.profile == nil %> 
    <li class="nav-item">
        <%= link_to 'Create Profile', new_profile_path, class:"nav-link" %>
    </li>     
    <% else %>
    <li class="nav-item">
        <%= link_to 'My Profile', profile_path(id: current_user.id), class:"nav-link" %>
    </li> 
    <li class="nav-item">
        <%= link_to "Deliver to: #{current_user.profile.address}", 
        profile_path(id: current_user.id), class:"nav-link delivery-address" %>
    </li>
    <% end %>
    <% else %>
    <li class="nav-item">
        <%= link_to 'Sign in', new_user_session_path, class:"nav-link" %>
    </li> 
    <li class="nav-item">
        <%= link_to 'Sign up', new_user_registration_path, class:"nav-link" %>
    </li>
    <% end %>     
    
    <li class="nav-item d-flex search">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success btn-sm btn-info" type="submit">search</button>  
    </li> 
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header'%>
    <div class="yield-container">
      <%= yield %>
    </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </body>
</html>